var quize=[
{
	"id": 1,
	"question":"Q1).Which of the following panel was appointed to put forward recommendations of GAAR?",
	"answere1":"A) Reddy panel",
	"answere2":	"B) P.Shome pane",
	"answere3":	"C) Rangarajan panel ",
	"answere4":	"D) None of these",
	"correctanswere":"B) P.Shome pane",
	          
},
{
	"id": 2,
	"question":"Q2) SDR is the currency of IMF, which is called as______________.also.",
	    "answere1":"A) White gold",
		"answere2": "B) Book keeping entry only ",
		"answere3":"C) Book keeping entry only",
		"answere4":"D) Paper gold ",
		"correctanswere":"D) Paper gold",
		
}	,          

{
	"id": 3,
	"question":"Q3) What is MCX-SX?.",
	 "answere1":"A) Third online trading share market in India",
		"answere2": "B) A new insurance company which is not registered with the government yet. ",
		"answere3":"C) Online trading market on paper only.",
		"answere4":"D) Online trading market dealing only in gold. ",
		"correctanswere":"A) Third online trading share market in India",
},
{
	"id": 4,
	"question":"Q4) Who regulates finance market in India?.",
	 "answere1":"A) Ministry of finance",
		"answere2": "B) Reserve bank of India ",
		"answere3":"C) Ministry of trade and commerce",
		"answere4":"D) SEBI ",
		"correctanswere":"D) SEBI",
},
{
	"id": 5,
	"question": "Q5) The famous Dilwara Temples are situated in",
	 "answere1":"A) Uttar Pradesh",
		"answere2": "B) Rajasthan ",
		"answere3":"C) Maharashtra",
		"answere4":"D) Madhya Pradesh ",
		"correctanswere":"B) Rajasthan",
},
{
	"id": 6,
	"question": "Q6) The headquarters of the National Power Training institute is located in",
	 "answere1":"A) Pune",
		"answere2": "B) Bhopal ",
		"answere3":"C) Faridabad",
		"answere4":"D) Lucknow ",
		"correctanswere":"C) Faridabad",
},
{
	"id": 7,
	"question": "Q7) The Dr. Babasaheb Ambedkar Marathwada University is at which of the following places?",
	 "answere1":"A) Aurangabad",
		"answere2": "B) Nanded ",
		"answere3":"C) Parbhani",
		"answere4":"D) Nagpur ",
		"correctanswere":"A) Aurangabad",
},
{
	"id": 8,
	"question": "Q8) The Indian Institute of Science is located at",
	 "answere1":"A) Kerala",
		"answere2": "B) Madras",
		"answere3":"C) Bangalore",
		"answere4":"D) New Delhi ",
		"correctanswere":"C) Bangalore",
},
{
	"id": 9,
	"question": "Q9) Which city is known as 'Electronic City of India'?",
	 "answere1":"A) Mumbai",
		"answere2": "B) Hyderabad ",
		"answere3":"C) Guragon",
		"answere4":"D) Bangalore ",
		"correctanswere":"D) Bangalore",
},
{
	"id": 10,
	"question": "Q10) Indian School of Mines is located in",
	 "answere1":"A) Dhanbad",
		"answere2": "B) Asansol",
		"answere3":"C) Tatanagar",
		"answere4":"D) Rourkela ",
		"correctanswere":"A) Dhanbad",
}
]